### PR TITLE
Tony/21_chrome_support

### LINKED ISSUE #21: MD-WIDGETS: Support CHROME target
## Description

Currently seeing a few issues with `flutter run -d chrome`. Otherwise it is working great. Thanks.

## Why

So that a web-based app functions fully with the package.

### VIDEO DOES NOT LOAD

Image

Image

### SUBMIT FAILS

Survey 3, tap on SUBMIT results in

Image

### PR DESCRIPTION
**Pull request by tonypioneer**
# Pull Request Details

## What issue does this PR address

- Fixed the issue that video cannot be played on Chrome.

- Link to associated issue: #21

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [ ] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [x] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Comment by gjwgit** [comment]
I am getting a black window on Linux. When I click Play the audio is heard but no video.

image

**Comment by tonypioneer** [comment]
> I am getting a black window on Linux. When I click Play the audio is heard but no video.
> 
> image

Thanks @gjwgit. I'll check it on Linux.

**Review by anushkavidanage — APPROVED** [review]

**Comment by gjwgit** [comment]
If my black screen on chrome is not seen on other OS then please merge this PR and have the Linux issue as a separate issue for resolution later on.

**Review by gjwgit — APPROVED** [review]

**Comment by tonypioneer** [comment]
> If my black screen on chrome is not seen on other OS then please merge this PR and have the Linux issue as a separate issue for resolution later on.

Hi @gjwgit, I will fix it in #30. This issue will be merged first.

**Pull request merged**
