### PR TITLE
Tony/10_refine

### LINKED ISSUE #10: MD WIDGETS: Refine the code and the structure of the repository
## Description

As discussed in the meeting, the code and the structure of the repository should be refined.

- [x] utils/text_utils.art -> justify_text.dart
- [x] Add example folder with README.md, pubspec.yaml and lib/main.dart
  - [x] A stand alone where I run `flutter create .; flutter run`
- [x] markdown_widget_builder.dart from utils to widgets
- [x] time_parser.dart to parse_time_string.dart
- [x] Remove the export of CommandParser.
- [x] markdown_widget_builder.dart needs the Widget documented

### PR DESCRIPTION
**Pull request by tonypioneer**
# Pull Request Details

## What issue does this PR address

- Added example folder with README.md, pubspec.yaml and lib/main.dart.
- Added documentation to Markdown Widget Builder.
- Renamed some dart files.

- Link to associated issue: #10

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Review by gjwgit — COMMENTED** [review]
Some small suggestions - if they are not so small, create a new issue and keep for the next version...

- [ ] For the example, can we have a very simple default SAVE method to simply save the survey to a local JSON file?
- [x] The video is beautiful! But at 25M perhaps it can be quite significantly reduced in size for publication? I got down below 1M and the video still looked good. I used `ffmpeg -i assets/media/sample_video_orig.mp4 -vcodec libx265 -crf 30 assets/media/sample_video.mp4`
- [x] Similarly the audio could be smaller/shorter. Very nice audio track too by the way.
- [x] Remove print() for the library source code.

**Comment by tonypioneer** [comment]
> Some small suggestions - if they are not so small, create a new issue and keep for the next version...
> 
> 
> 
> - [ ] For the example, can we have a very simple default SAVE method to simply save the survey to a local JSON file?
> 
> - [ ] The video is beautiful! But at 25M perhaps it can be quite significantly reduced in size for publication? I got down below 1M and the video still looked good. I used `ffmpeg -i assets/media/sample_video_orig.mp4 -vcodec libx265 -crf 30 assets/media/sample_video.mp4`
> 
> - [ ] Similarly the audio could be smaller/shorter. Very nice audio track too by the way.

Thanks @gjwgit, I'll create a new issue to fix them.

**Comment by tonypioneer** [comment]
> Some small suggestions - if they are not so small, create a new issue and keep for the next version...
> 
> * [ ]  For the example, can we have a very simple default SAVE method to simply save the survey to a local JSON file?
> * [x]  The video is beautiful! But at 25M perhaps it can be quite significantly reduced in size for publication? I got down below 1M and the video still looked good. I used `ffmpeg -i assets/media/sample_video_orig.mp4 -vcodec libx265 -crf 30 assets/media/sample_video.mp4`
> * [x]  Similarly the audio could be smaller/shorter. Very nice audio track too by the way.
> * [x]  Remove print() for the library source code.

I created #17 to implement saving user input data as a local JSON file, and will fix other issues in this branch.

**Comment by gjwgit** [comment]
I am seeing the markup in the rendered page:

image

**Comment by gjwgit** [comment]
```
12 Nov 10:27:26 gjw@kadesh ~markdown_widgets/example$ flutter analyze
Analyzing example...                                            

   info • Dangling library doc comment • lib/main.dart:1:1 • dangling_library_doc_comments

1 issue found. (ran in 1.7s)
```

**Comment by gjwgit** [comment]
```
12 Nov 10:28:50 gjw@kadesh ~/projects/markdown_widgets$ flutter analyze
Analyzing markdown_widgets...                                   

   info • Dangling library doc comment • example/lib/main.dart:1:1 • dangling_library_doc_comments
warning • The value of the field '_inputFieldKeys' isn't used • lib/src/utils/command_parser.dart:56:54 • unused_field

2 issues found. (ran in 1.5s)
```

**Comment by tonypioneer** [comment]
> I am seeing the markup in the rendered page:
> 
> image

Thanks @gjwgit, I'll check it.

**Comment by gjwgit** [comment]
I am getting unused code with the following. Some are expected, but a few others are not. Could you have a look. Thanks

```
dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib
```

**Comment by tonypioneer** [comment]
> I am getting unused code with the following. Some are expected, but a few others are not. Could you have a look. Thanks
> 
> ```
> dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib
> ```

I fixed the unused code found by `flutter analyze`, but for the unused variables and classes identified by `dart run dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib`, I checked them one by one, since `markdown_widgets` is a package, these classes and variables, although not explicitly called, need to remain there.

**Comment by tonypioneer** [comment]
> I am seeing the markup in the rendered page:
> 
> image

This issue has been fixed.

**Review by gjwgit — APPROVED** [review]

**Comment by gjwgit** [comment]
The new audio track is 'scratchy'. Something a little more pleasant would be nice.

**Comment by tonypioneer** [comment]
> The new audio track is 'scratchy'. Something a little more pleasant would be nice.

Hi @gjwgit, I replaced it with a sound track download from https://pixabay.com/music/search/no%20copyright%20music/, which is a copyright and royalty free music.

**Review by anushkavidanage — APPROVED** [review]
Looks good. Thanks

**Pull request merged**
