### PR TITLE
Tony/54_escape_characters

### LINKED ISSUE #54: MD WIDGETS: Use escape characters to represent brackets in radio button and checkbox labels
## Description

Currently, right brackets cannot appear in the label text of the `%% Radio` and `%% Checkbox` commands because they will be mistakenly recognised as parameter separators and command terminators. The code needs to be modified to support displaying brackets using escape characters.

The following is a sample markdown code.

```markdown
%% Checkbox(Question 1,1,"None")
%% Checkbox(Question 1,2,"Scalp discomfort (at site of treatment)",Hidden 2)
%% Checkbox(Question 1,3,"Headache",Hidden 3)
%% Checkbox(Question 1,4,"Neck Pain",Hidden 4)
%% Checkbox(Question 1,5,"Muscle aches",Hidden 5)
%% Checkbox(Question 1,6,"Dizziness",Hidden 6)
%% Checkbox(Question 1,7,"Nausea",Hidden 7)
%% Checkbox(Question 1,8,"Tiredness/Fatigue",Hidden 8)
%% Checkbox(Question 1,9,"Flashing lights (phosphene perception)",Hidden 9)
%% Checkbox(Question 1,10,"Other",Hidden 10)
```

The following is the rendered page.

image

### PR DESCRIPTION
**Pull request by tonypioneer**
# Pull Request Details

## What issue does this PR address

- Add support for escaped left and right brackets.

- Link to associated issue: #54 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [ ] Changes adhere to the team style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added 2 reviewers (or 1 for private repositories then they add another)

## Finalising

Once PR discussion is complete and 2 reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev

### CODE REVIEW

**Comment by anushkavidanage** [comment]
I am getting the following error. 

error

**Comment by tonypioneer** [comment]
> I am getting the following error.
> 
> error

Hi @anushkavidanage, thank you for your feedback. Could you share your markdown code for this question? I'll analyse the reason. Thank you very much.

**Comment by anushkavidanage** [comment]
Here's the markdown code.

```
3. The following are two groups of checkboxes. This is Question 3. Multiple 
   options can be selected.

%% Checkbox(Question 3,1,"Option 1 This is a long option that may wrap to the
next line if it needs to. When wrapping it does so indented to align the
paragraph. This example also demonstrates the use of escape characters, such
as \".")

%% Checkbox(Question 3,2,"Option 2. If you choose this option, you will need to
answer another follow-up question.",Hidden 3)

%% Checkbox(Question 3,3,"Option 3")

%% Checkbox(Question 3,4,"Option 4 (details about option 4)")

%% Checkbox(Question 3,5,"Option 5")

%% Checkbox(Question 3,6,"Option 6")

%% Hidden-Begin(Hidden 3)
This is a follow-up question for Option 2.
%% InputML(Question 3.2)
%% Hidden-End
```

**Comment by tonypioneer** [comment]
> Here's the markdown code.
> 
> ```
> 3. The following are two groups of checkboxes. This is Question 3. Multiple 
>    options can be selected.
> 
> %% Checkbox(Question 3,1,"Option 1 This is a long option that may wrap to the
> next line if it needs to. When wrapping it does so indented to align the
> paragraph. This example also demonstrates the use of escape characters, such
> as \".")
> 
> %% Checkbox(Question 3,2,"Option 2. If you choose this option, you will need to
> answer another follow-up question.",Hidden 3)
> 
> %% Checkbox(Question 3,3,"Option 3")
> 
> %% Checkbox(Question 3,4,"Option 4 (details about option 4)")
> 
> %% Checkbox(Question 3,5,"Option 5")
> 
> %% Checkbox(Question 3,6,"Option 6")
> 
> %% Hidden-Begin(Hidden 3)
> This is a follow-up question for Option 2.
> %% InputML(Question 3.2)
> %% Hidden-End
> ```

Hi @anushkavidanage, thank you for sharing your markdown code. I think you can use escape characters `\(` and `\)` to represent the brackets as below.

```
%% Checkbox(Question 3,4,"Option 4 \(details about option 4\)")
```

image

In this ticket (#54), I defined 3 escape characters `\(`, `\)` and `\"` to represent '(', ')' and '"' respectively, because using these 3 characters directly may cause parsing problems.

**Comment by anushkavidanage** [comment]
Thanks for the clarification Tony. That worked. Thanks.

**Review by anushkavidanage — APPROVED** [review]

**Comment by cdawei** [comment]
Hi Tony, using the markdown code below, I got `\(` and `\)` as shown in the screenshot, is that expected behaviour?
```
%% Dropdown(Dropdown Menu)
- Option 1 \(Hello\)
- Option 2
- Option 3
- Option 4
```

image

**Comment by tonypioneer** [comment]
> Hi Tony, using the markdown code below, I got `\(` and `\)` as shown in the screenshot, is that expected behaviour?
> 
> ```
> %% Dropdown(Dropdown Menu)
> - Option 1 \(Hello\)
> - Option 2
> - Option 3
> - Option 4
> ```
> 
> image

Hi @cdawei, the escape characters are just designed for radio buttons and checkboxes. Because after the %% Radio command and the %% Checkbox command, there is an argument list, which uses brackets and quotation marks to mark the beginning and the end of the argument list and the string inside it.

**Comment by cdawei** [comment]
> Hi @cdawei, the escape characters are just designed for radio buttons and checkboxes. Because after the %% Radio command and the %% Checkbox command, there is an argument list, which uses brackets and quotation marks to mark the beginning and the end of the argument list and the string inside it.

Thanks Tony for clarifying. If this is clearly described in the user manual then all good.

**Review by cdawei — APPROVED** [review]

**Comment by tonypioneer** [comment]
> > Hi @cdawei, the escape characters are just designed for radio buttons and checkboxes. Because after the %% Radio command and the %% Checkbox command, there is an argument list, which uses brackets and quotation marks to mark the beginning and the end of the argument list and the string inside it.
> 
> Thanks Tony for clarifying. If this is clearly described in the user manual then all good.

Thanks @cdawei. I updated the README file.

**Pull request merged**
